# Generated by Django 4.2.11 on 2024-04-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_contato_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='datadenasc',
            field=models.DateField(default='2000-01-01', verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(default='email@default', max_length=254),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
