# Generated by Django 4.2.11 on 2024-04-28 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_contato_datadenasc_alter_contato_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='datadenasc',
            field=models.DateField(default=datetime.date(2024, 4, 28), verbose_name='Data de nascimento'),
        ),
    ]
