# Generated by Django 4.2.11 on 2024-04-28 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_contato_datadenasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='datadenasc',
            field=models.DateField(default=datetime.datetime(2024, 4, 28, 20, 25, 50, 420787, tzinfo=datetime.timezone.utc), verbose_name='Data de nascimento'),
        ),
    ]
