# Generated by Django 4.2.11 on 2024-04-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_contato_datadenasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='datadenasc',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
    ]
