# Generated by Django 4.2.11 on 2024-04-29 14:03

import agenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_alter_contato_datadenasc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(default='agenda/fotos/profilebase.jpeg', upload_to=agenda.models.diretorio_imagens),
        ),
    ]
